### PR TITLE
Update report_table.html

### PR DESCRIPTION
**Pull request by damian1976**
```thead``` tag causes table header in report table to be displayed twice. Please check if ot can be safely removed.

### CODE REVIEW

**Comment by mkurek** [comment]
It's not valid solution - removing thead tag does not solve the real problem here.

First of all your problem is that additional header is not hidden by default. To fix this add `$headerFixed.hide();` in table_fixed_header.js in `init` function.

BUT - actually it doesn't fix anything because in new Scrooge there is fixed top bar, what makes this fixed header not working at all. So for now the best way to (temporary) solve this is removing `fixed-header` css class from `table` in report_table.html and/or removing including `scrooge/js/table_fixed_header.js` in base.html template. 

Please follow these instructions, correct your PR and then it'll be merged (as a temporary fix) and we'll think how to solve this problem from scratch (and think if fixed header is really necessary with table scrolling).

**Comment by mkurek** [comment]
Now squash all commits into one and add some extensive commit message about changes.

**Comment by kula1922** [comment]
src/ralph_scrooge/templates/ralph_scrooge/report_table.html
src/ralph_scrooge/templates/ralph_scrooge/base.html

This 2 files are you feature so plx pull current develop, path it and then make new pull request.

**Comment by damian1976** [comment]
You can ignore these changes. They are not important.

**Comment by vi4m** [comment]
@mkurek decide here

**Comment by mkurek** [comment]
@damian1976 if you want it to be merged please make a pull request only with your changes in src/ralph_scrooge/templates/ralph_scrooge/base.html and src/ralph_scrooge/templates/ralph_scrooge/report_table.html

**Pull request closed without merging**
