### PR TITLE
Added migration which replaces scrooge warehouses with assets datacenters.

### PR DESCRIPTION
**Pull request by ghost**
Scrooge warehouses was populated with data from assets warehouses.
Since assets have new datacenter model (which is more relevant data source
now) the data should be migrated, and this change does it.

Depends on: https://github.com/allegro/ralph_pricing/pull/390 (because of migration number)
@mkurek @ar4s

### CODE REVIEW

**Comment by mkurek** [comment]
:ok:

**Comment by mkurek** [comment]
@xliiv please bump migration number to 0023 to match another db migrations (https://github.com/allegro/ralph_pricing/labels/db_migration)

**Comment by ghost** [comment]
@mkurek done

**Comment by mkurek** [comment]
:ok:

**Comment by ar4s** [comment]
:ok:

**Pull request merged**
