### PR TITLE
Openstack ceilometer plugin with MongoDB support

### PR DESCRIPTION
**Pull request by damian1976**

### CODE REVIEW

**Comment by damian1976** [comment]
It would be great to update existing openstack_ceilometer.py file name to openstack_mysql_ceilometer.py, so that the file names point to database names the plugins support

**Comment by mkurek** [comment]
@damian1976 feel free to rename this file.

**Comment by mkurek** [comment]
Please fix flake8 errors: https://travis-ci.org/allegro/ralph_pricing/jobs/53055626

**Comment by mkurek** [comment]
Could you squash it into one commit?

**Comment by kula1922** [comment]
:ok:

**Pull request merged**
