### PR TITLE
added active flag to base usage type

### PR DESCRIPTION
**Pull request by mkurek**
added active flag to base usage type

### CODE REVIEW

**Comment by mkurek** [comment]
Notice that migration number is bumped to 0022 to match partitioning migrations from https://github.com/allegro/ralph_pricing/pull/437

**Comment by kula1922** [comment]
Team:
ralph_scrooge/report/base_plugin_report:181
ralph_scrooge/report/allocationadmin:106
ralph_scrooge/report/allocationadmin:316
ralph_scrooge/report/allocationclient:305
ralph_scrooge/report/base:95
ralph_scrooge/sidebar_menus:175
ralph_scrooge/tests/plugins/cost/test_team:47

**Comment by kula1922** [comment]
ExtraCostType:
plugins/cost/support.py:65
report/base_plugin_report.py:64
rest/allocationadmin.py:58
rest/allocationadmin.py:236
tests/utils/factory.py:227 <- active as default

DynamicExtraCostType:
report/base_plugin_report.py:79
rest/allocationadmin.py:85
rest/allocationadmin.py:291
tests/utils/factory.py:253

PricingService:
api:py:316
api:py:467
models/service.py:254
report/base_plugin_report.py:155
rest/allocationclient.py:51
rest/allocationclient.py:55 <--- when create then active should be as true
tests/utils/factory.py:305

Team:
report/base_plugin_report.py:181
rest/allocationadmin.py:316
rest/allocationadmin.py:106
rest/allocationclient.py:305
rest/base.py:95
sidebar_menus.py:175
tests/plugins/cost/test_team.py:47
tests/utils/factory.py: 277

UsageType:
api:py:363
forms.py:283
management/commands/scrooge_statistics.py:171
management/commands/scrooge_tenants_instances.py:120
plugins/collect/asset.py:247
plugins/collect/blade_server.py:71
plugins/collect/netflow.py: 277
plugins/collect/openstack_ceilometer.py:58
plugins/collect/openstack_simple_usage.py:61
plugins/collect/san.py:71
plugins/collect/share.py:74
plugins/collect/virtual.py:183
plugins/collect/virtual.py:192
plugins/collect/virtual.py:201
plugins/cost/team.py:219
report/base_plugin_report.py:88
report/base_plugin_report.py:121
rest/allocationadmin.py:131
rest/allocationadmin.py:212
rest/allocationclient.py:75


Maybe overload get_or_create() or save() and when active is not pas

**Comment by mkurek** [comment]
@kula1922 i've added default objects manager which filter only active items, so there is no need to change every place where UsageType, ExtraCostType etc are used.

**Comment by ar4s** [comment]
:ok:

**Comment by ghost** [comment]
:ok:

**Pull request merged**
